[App]
Name = "ai.h2o.wave.template"
Version = "0.0.1"
Title = "Template Application"
Description = ""
Category = ""
Keywords = []
LongDescription = "docs/app_store_description.md"

[Runtime]
Module = "src.app"
